### PR TITLE
Change name to ContentReplacerWebpackPlugin

### PR DESCRIPTION
**Pull request by Phinneas**
# Pull request

### What kind of change does this PR introduce?

Changed name of web pack plugin from ContentReplacer to ContentReplacerWebpackPlugin.

### Did you add tests for your changes?

Yes

### Summary

Follow naming convention

### Other information

Issue #21

### CODE REVIEW

**Comment by Phinneas** [comment]
Changed name of web pack plugin from ContentReplacer to ContentReplacerWebpackPlugin.

**Comment by iGitScor** [comment]
You also need to:
- Modify the documentation `README.md`

When the pull request will be merged, I'll create the alias system.

**Comment by iGitScor** [comment]
Hi @Phinneas,

you have a conflict in your `README.md` file. Do you need help in the conflict resolution ?

**Comment by Phinneas** [comment]
Let me look at this today. I think I can fix this. 

Open sesame.

**Comment by Phinneas** [comment]
I think I fixed it.

**Comment by Phinneas** [comment]
What does invalid mean in this case? Was the work rejected?

**Pull request closed without merging**
