### PR TITLE
Use less strict mode for dependencies

### PR DESCRIPTION
**Pull request by dmukherjee**
# Pull request

### What kind of change does this PR introduce?
This PR updates dev dependencies in package.json in less strict mode

### Did you add tests for your changes?
No
### Summary
The dependencies in less strict mode will enable the contributors to use more recent versions of the dependencies whilst guarding against updating major version of the dependencies which might have a higher chance of breaking the existing implementation. 

The dev dependencies now uses Caret Ranges (example: ^1.2.3). This allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. This allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X. 

### Other information
This PR addresses the issue https://github.com/iGitScor/webpack-content-replacer-plugin/issues/31
The dependency format details can be found here: https://docs.npmjs.com/misc/semver

### CODE REVIEW

**Comment by dmukherjee** [comment]
Hi @iGitScor! This is my first open source PR. Please review and let me know if anything needs to be modified. I will be happy to do so at my earliest.

**Comment by iGitScor** [comment]
Hi @dmukherjee,

thank you for this pull request ❤️ !
As the build is still valid, everything seems perfect.

**Review by iGitScor — APPROVED** [review]

**Comment by iGitScor** [comment]
@dmukherjee,

I'll be glad to welcome you in the contributor team. Please tell me if you're interested and what kind of development you would like to do

**Comment by dmukherjee** [comment]
@iGitScor,

Thank you so much! I would be happy to contribute. I will be interested in any development related to node.js, ES6 although I do not have a very strong preference. Anywhere you need help with, please let me know. I might not be an expert 😄 with all front-end techs but I certainly will do my best to find out the solution.

**Comment by iGitScor** [comment]
Hi @dmukherjee,

I'm working on several projects on which I'm looking for contributors. Do you want/think a label ES6/nodejs is a good idea ? does this idea will help you ?

You can have a look to [this list](https://github.com/search?q=topic%3Afirstpr-friendly&type=Repositories)

Thank you

**Comment by dmukherjee** [comment]
Hi @iGitScor It would be great if you can label when adding new issues if you have the bandwidth :) Thank you for sharing the list. This is very helpful. I will take a look if I can pick up something.

**Comment by iGitScor** [comment]
@dmukherjee, I've started to flag nodejs/ES6 issues. I've also other ideas for those projects so I'll add the label automatically when the purpose is ES6 development

Thank you for this idea 😉 and welcome !

**Comment by dmukherjee** [comment]
@iGitScor This is great 😄 👍 . Thanks so much!!

**Pull request merged**
