### PR TITLE
Improve documentation for developing/installing

### PR DESCRIPTION
**Pull request by iGitScor**
# Pull request

### What kind of change does this PR introduce?

No change for the library, only documentation

### Did you add tests for your changes?

Not relevant to add test

### Summary

Improve documentation for new contributors and also developers which need this plugin in their webpack build.

### Other information

Issue #19 

### GIF

Britney

### CODE REVIEW

**Comment by iGitScor** [comment]
Hi @YQBird, do you want to be involved in code review ? Have you ever done that before ?

**Comment by YQBird** [comment]
Hi @iGitScor. Never done this for a Open Source Project before. Really want to join code review!

**Comment by iGitScor** [comment]
Ok, I guess you have done code review for non open source project before.
For documentation and breaking change development, I would like you to check pull request with all the contributors (I will mention it in the documentation) - [Github documentation here](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/)

If the pull request is not checked after a couple of days, it can be merged but comments are always welcomed.
If the pull request is refused, no merge is allowed.

Are you comfortable with these rules ?

**Comment by YQBird** [comment]
Sounds good to me.

**Review by YQBird — APPROVED** [review]
Looks Good!

**Pull request merged**
